#!/usr/bin/env python3

import socket
import threading
import time
import random
import sys

from proton_py.signal_pb2 import (
  Signal,
  ListFloats,
  ListDoubles,
  ListBools,
  ListInt32s,
  ListInt64s,
  ListStrings,
  ListUint32s,
  ListUint64s
)
from proton_py.proton_pb2 import Proton

from google.protobuf.message import DecodeError

UDP_IP = '127.0.0.1'
MCU_IP = '127.0.0.1'
PROTON_UDP_PORT = 11417
PROTON_SEND_PORT = 11417

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP
sock.bind((UDP_IP, PROTON_UDP_PORT))


class ProtonProcess():
    def __init__(self):
        self.t = threading.Thread(target=self.send_float_list, daemon=True)
        #self.t.start()
        self.sock_read()

    def send_float_list(self):
        while(True):
            proton = Proton()
            proton.id = 0x200
            proton.signals.extend([
              Signal(
                  bool_value=random.randrange(0, 2)
              ),
              Signal(
                  double_value=random.random()
              ),
              Signal(
                  float_value=random.random()
              ),
              Signal(
                  int32_value=random.randint(-0x7FFFFFFF, 0x7FFFFFFF)
              ),
              Signal(
                  int64_value=random.randint(-0x7FFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFF)
              ),
              Signal(
                  uint32_value=random.randint(0, 0xFFFFFFFF)
              ),
              Signal(
                  uint64_value=random.randint(0, 0xFFFFFFFFFFFFFFFF)
              ),
              Signal(
                  string_value='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
              ),
              Signal(
                  bytes_value=bytes([random.randint(0, 255) for i in range(0, random.randint(0, 64))])
              ),
              Signal(
                    list_double_value=ListDoubles(
                        doubles=[random.random() for i in range(0, 10)])),
              Signal(
                    list_float_value=ListFloats(
                        floats=[random.random() for i in range(0, 10)])),
              Signal(
                    list_int32_value=ListInt32s(
                        int32s=[random.randint(-0x7FFFFFFF, 0x7FFFFFFF) for i in range(0, 10)])),
              Signal(
                    list_int64_value=ListInt64s(
                        int64s=[random.randint(-0x7FFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFF) for i in range(0, 10)])),
            ])

            print(f'Sent {proton.ByteSize()}')
            #print(proton)

            sock.sendto(proton.SerializeToString(), (MCU_IP, PROTON_SEND_PORT))
            time.sleep(1)

    def sock_read(self):
      while(True):
          data, addr = sock.recvfrom(1000)
          print('~~~ Protobuf Received ~~~')
          print(data)
          print(f'Data len {len(data)}')
          print()

          proton = Proton()
          try:
            Proton.ParseFromString(proton, data)
            print('~~~ Deserialized to protobuf ~~~')
            print(proton)
            print(f'Length {proton.ByteSize()}')
            print()
          except DecodeError:
              print('Decode Error')


          # print('~~~ Indexed ~~~')
          # i = 0
          # for data in pb.data:
          #     value = None
          #     match data.WhichOneof('data'):
          #         case 'float_value':
          #             value = data.float_value
          #         case 'string_value':
          #             value = data.string_value
          #         case 'bool_value':
          #             value = data.bool_value

          #     print(f'Index: {i} Type: {data.WhichOneof('data')} Data: {value}')
          #     i += 1

          print('---------------------------------------')


if __name__ == '__main__':
    proton = ProtonProcess()
