#!/usr/bin/env python3

import socket
from proton_py.signal_pb2 import Signal, ListDoubles, ListStrings
from proton_py.bundle_pb2 import Bundle

UDP_IP = '127.0.0.1'
UDP_PORT = 11411

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def make_pb():
    proton = Bundle(id=0x01)

    float_data = Signal(float_value=123.456)
    string_data = Signal(string_value='test')
    bool_data = Signal(bool_value=True)
    double_array = Signal(list_double_value=ListDoubles(doubles=[0.1, 0.2, 0.3]))
    string_array = Signal(list_string_value=ListStrings(strings=[
       '2.7.0',
       'A300',
       'Rev3'
    ]))
    bytes_data = Signal(bytes_value=bytes([0x1, 0x2, 0x3]))

    proton.signals.extend([
      #  float_data,
      #  string_data,
      bool_data,
      # float_data,
      string_data,
      bool_data,
      string_data,
      string_data,
      bool_data,
      bool_data,
      float_data,
      float_data,
      string_data,
      double_array,
      float_data,
      string_array,
      bytes_data
    ])

    return proton

if __name__ == '__main__':
  try:
      proton = make_pb()
      sock.sendto(proton.SerializeToString(), (UDP_IP, UDP_PORT))
  except KeyboardInterrupt:
     pass