#!/usr/bin/env python3

import socket
from proton_py.signal_pb2 import Signal
from proton_py.proton_pb2 import Proton

UDP_IP = '127.0.0.1'
PROTON_UDP_PORT = 11411
SDO_UDP_PORT = 11412

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, SDO_UDP_PORT))

if __name__ == '__main__':
  try:
      while(True):
          data, addr = sock.recvfrom(100)
          print('~~~ Protobuf Received ~~~')
          print(data)
          print()

          proton = Proton()
          Proton.ParseFromString(proton, data)

          print('~~~ Deserialized to protobuf ~~~')
          print()
          print(proton)
          print()

          proton2 = Proton()
          proton2.id = proton.id + 1
          proton2.signals.extend([Signal(string_value='response')])
          sock.sendto(proton2.SerializeToString(), (UDP_IP, PROTON_UDP_PORT))
  except KeyboardInterrupt:
     pass