# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x06proton\"\x1e\n\x0bListDoubles\x12\x0f\n\x07\x64oubles\x18\x01 \x03(\x01\"\x1c\n\nListFloats\x12\x0e\n\x06\x66loats\x18\x01 \x03(\x02\"\x1c\n\nListInt32s\x12\x0e\n\x06int32s\x18\x01 \x03(\x05\"\x1c\n\nListInt64s\x12\x0e\n\x06int64s\x18\x01 \x03(\x03\"\x1e\n\x0bListUint32s\x12\x0f\n\x07uint32s\x18\x01 \x03(\r\"\x1e\n\x0bListUint64s\x12\x0f\n\x07uint64s\x18\x01 \x03(\x04\"\x1a\n\tListBools\x12\r\n\x05\x62ools\x18\x01 \x03(\x08\"\x1e\n\x0bListStrings\x12\x0f\n\x07strings\x18\x01 \x03(\t\"\xea\x04\n\x06Signal\x12\x16\n\x0c\x64ouble_value\x18\x01 \x01(\x01H\x00\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x02H\x00\x12\x15\n\x0bint32_value\x18\x03 \x01(\x05H\x00\x12\x15\n\x0bint64_value\x18\x04 \x01(\x03H\x00\x12\x16\n\x0cuint32_value\x18\x05 \x01(\rH\x00\x12\x16\n\x0cuint64_value\x18\x06 \x01(\x04H\x00\x12\x14\n\nbool_value\x18\x07 \x01(\x08H\x00\x12\x16\n\x0cstring_value\x18\x08 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\t \x01(\x0cH\x00\x12\x30\n\x11list_double_value\x18\n \x01(\x0b\x32\x13.proton.ListDoublesH\x00\x12.\n\x10list_float_value\x18\x0b \x01(\x0b\x32\x12.proton.ListFloatsH\x00\x12.\n\x10list_int32_value\x18\x0c \x01(\x0b\x32\x12.proton.ListInt32sH\x00\x12.\n\x10list_int64_value\x18\r \x01(\x0b\x32\x12.proton.ListInt64sH\x00\x12\x30\n\x11list_uint32_value\x18\x0e \x01(\x0b\x32\x13.proton.ListUint32sH\x00\x12\x30\n\x11list_uint64_value\x18\x0f \x01(\x0b\x32\x13.proton.ListUint64sH\x00\x12,\n\x0flist_bool_value\x18\x10 \x01(\x0b\x32\x11.proton.ListBoolsH\x00\x12\x30\n\x11list_string_value\x18\x11 \x01(\x0b\x32\x13.proton.ListStringsH\x00\x42\x08\n\x06signalb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTDOUBLES._serialized_start=24
  _LISTDOUBLES._serialized_end=54
  _LISTFLOATS._serialized_start=56
  _LISTFLOATS._serialized_end=84
  _LISTINT32S._serialized_start=86
  _LISTINT32S._serialized_end=114
  _LISTINT64S._serialized_start=116
  _LISTINT64S._serialized_end=144
  _LISTUINT32S._serialized_start=146
  _LISTUINT32S._serialized_end=176
  _LISTUINT64S._serialized_start=178
  _LISTUINT64S._serialized_end=208
  _LISTBOOLS._serialized_start=210
  _LISTBOOLS._serialized_end=236
  _LISTSTRINGS._serialized_start=238
  _LISTSTRINGS._serialized_end=268
  _SIGNAL._serialized_start=271
  _SIGNAL._serialized_end=889
# @@protoc_insertion_point(module_scope)
